# Generated by Django 5.1.2 on 2024-11-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='requirement',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
