# Generated by Django 5.1.2 on 2024-11-20 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_service_requirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='citizen_id',
        ),
    ]
