# Generated by Django 5.1.2 on 2024-11-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_citizen_citizen_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='pub_id',
        ),
        migrations.AddField(
            model_name='citizen',
            name='phone_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
