# Generated by Django 5.1.2 on 2024-11-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_remove_publication_pub_id_citizen_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='files',
            field=models.FileField(upload_to='publication/'),
        ),
    ]
