# Generated by Django 5.1.2 on 2024-11-25 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_colline_commune_commune_province'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CitizenParent',
        ),
        migrations.DeleteModel(
            name='IdCardRegistration',
        ),
        migrations.AddField(
            model_name='citizen',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_of_father', to='management.citizen'),
        ),
        migrations.AddField(
            model_name='citizen',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_of_mother', to='management.citizen'),
        ),
        migrations.AddField(
            model_name='lostidcardreport',
            name='report',
            field=models.TextField(null=True),
        ),
    ]
