# Generated by Django 5.1.2 on 2024-11-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_delete_citizenparent_delete_idcardregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredidcardapplication',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
