# Generated by Django 5.1.2 on 2024-11-27 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_colline_chief_alter_commune_chief_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostidcardreport',
            name='citizen_id',
        ),
        migrations.RemoveField(
            model_name='registeredidcard',
            name='citizen_id',
        ),
        migrations.RemoveField(
            model_name='registeredidcardapplication',
            name='citizen_id',
        ),
        migrations.AddField(
            model_name='citizen',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lostidcardreport',
            name='citizen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.citizen'),
        ),
        migrations.AddField(
            model_name='registeredidcard',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.registeredidcardapplication'),
        ),
        migrations.AddField(
            model_name='registeredidcard',
            name='citizen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.citizen'),
        ),
    ]
