# Generated by Django 5.1.2 on 2024-11-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_lostidcardreport_colline_lostidcardreport_commune_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='registeredidcardapplication',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
