# Generated by Django 5.1.2 on 2024-11-27 10:43

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_rename_phone_number_citizen_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostidcardreport',
            name='card_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='registeredidcard',
            name='card_id',
            field=models.IntegerField(default=management.models.generate_random_card_id),
        ),
    ]
