# Generated by Django 5.1.2 on 2024-12-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_chat_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
